run:
	python3 main.py
#path:
#	export PYTHONPATH="/home/rasulabduvaitov/Desktop/uptimoll/dinamic_b/app/":$PYTHONPATH && export PYTHONPATH="/home/rasulabduvaitov/Desktop/uptimoll/dinamic_b/app/api":$PYTHONPATH
