"""add ru section

Revision ID: 301c2b592be4
Revises: 690a981be957
Create Date: 2024-04-21 21:18:49.504216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301c2b592be4'
down_revision: Union[str, None] = '690a981be957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('title_ru', sa.String(), nullable=True))
    op.add_column('course', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('course', sa.Column('type_ru', sa.String(), nullable=True))
    op.add_column('course', sa.Column('sub_title_ru', sa.String(), nullable=True))
    op.add_column('for_who', sa.Column('title_ru', sa.String(), nullable=True))
    op.add_column('for_who', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('learn_format', sa.Column('group_ru', sa.String(), nullable=True))
    op.add_column('learn_format', sa.Column('desc_ru', sa.String(), nullable=True))
    op.add_column('learn_format', sa.Column('desc_2_ru', sa.String(), nullable=True))
    op.add_column('start_group', sa.Column('when_start_ru', sa.String(), nullable=False))
    op.add_column('start_group', sa.Column('group_lang_ru', sa.String(), nullable=True))
    op.add_column('start_group', sa.Column('time_start_ru', sa.String(), nullable=True))
    op.add_column('start_group', sa.Column('time_end_ru', sa.String(), nullable=True))
    op.add_column('start_group', sa.Column('weeks_ru', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('start_group', 'weeks_ru')
    op.drop_column('start_group', 'time_end_ru')
    op.drop_column('start_group', 'time_start_ru')
    op.drop_column('start_group', 'group_lang_ru')
    op.drop_column('start_group', 'when_start_ru')
    op.drop_column('learn_format', 'desc_2_ru')
    op.drop_column('learn_format', 'desc_ru')
    op.drop_column('learn_format', 'group_ru')
    op.drop_column('for_who', 'description_ru')
    op.drop_column('for_who', 'title_ru')
    op.drop_column('course', 'sub_title_ru')
    op.drop_column('course', 'type_ru')
    op.drop_column('course', 'description_ru')
    op.drop_column('course', 'title_ru')
    # ### end Alembic commands ###
