"""add column teaher

Revision ID: 690a981be957
Revises: 9b8f3a518128
Create Date: 2024-04-21 17:39:04.927658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690a981be957'
down_revision: Union[str, None] = '9b8f3a518128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('course', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'course')
    # ### end Alembic commands ###
