"""add ru section

Revision ID: e949e9e0dc9e
Revises: 301c2b592be4
Create Date: 2024-04-22 11:40:01.972569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e949e9e0dc9e'
down_revision: Union[str, None] = '301c2b592be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name_ru', sa.String(), nullable=False))
    op.add_column('teacher', sa.Column('course_ru', sa.String(), nullable=False))
    op.add_column('teacher', sa.Column('description_ru', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'description_ru')
    op.drop_column('teacher', 'course_ru')
    op.drop_column('teacher', 'name_ru')
    # ### end Alembic commands ###
