"""delete photo

Revision ID: 43804dbbb0cb
Revises: f9a0df1bf2bc
Create Date: 2023-08-25 17:55:05.959808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43804dbbb0cb'
down_revision: Union[str, None] = 'f9a0df1bf2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'for_who_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('for_who_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
