"""on delete

Revision ID: 5890d77b6325
Revises: 77cb3a647406
Create Date: 2024-04-12 22:25:13.145749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5890d77b6325'
down_revision: Union[str, None] = '77cb3a647406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('for_who_course_id_fkey', 'for_who', type_='foreignkey')
    op.create_foreign_key(None, 'for_who', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('learn_format_course_id_fkey', 'learn_format', type_='foreignkey')
    op.create_foreign_key(None, 'learn_format', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('start_group_course_id_fkey', 'start_group', type_='foreignkey')
    op.create_foreign_key(None, 'start_group', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('student_work_course_id_fkey', 'student_work', type_='foreignkey')
    op.create_foreign_key(None, 'student_work', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_work', type_='foreignkey')
    op.create_foreign_key('student_work_course_id_fkey', 'student_work', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'start_group', type_='foreignkey')
    op.create_foreign_key('start_group_course_id_fkey', 'start_group', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'learn_format', type_='foreignkey')
    op.create_foreign_key('learn_format_course_id_fkey', 'learn_format', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'for_who', type_='foreignkey')
    op.create_foreign_key('for_who_course_id_fkey', 'for_who', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
