"""change the row

Revision ID: a02772c58485
Revises: 581e335ad1dd
Create Date: 2023-09-20 14:23:33.183699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02772c58485'
down_revision: Union[str, None] = '581e335ad1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('sub_title', sa.String(), nullable=True))
    op.drop_column('for_who', 'sub_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('for_who', sa.Column('sub_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('course', 'sub_title')
    # ### end Alembic commands ###
