"""add tables all fk

Revision ID: bd3b5a41befb
Revises: 42e794ae829a
Create Date: 2023-08-23 11:28:11.369252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3b5a41befb'
down_revision: Union[str, None] = '42e794ae829a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('desc_2', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learn_format_id'), 'learn_format', ['id'], unique=False)
    op.create_table('student_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_work_id'), 'student_work', ['id'], unique=False)
    op.drop_index('ix_learning_fromat_id', table_name='learning_fromat')
    op.drop_table('learning_fromat')
    op.drop_index('ix_student-work_id', table_name='student-work')
    op.drop_table('student-work')
    op.add_column('course', sa.Column('for_who', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('start_group', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('learn_format', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('student_work', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'learn_format', ['learn_format'], ['id'])
    op.create_foreign_key(None, 'course', 'student_work', ['student_work'], ['id'])
    op.create_foreign_key(None, 'course', 'for_who', ['for_who'], ['id'])
    op.create_foreign_key(None, 'course', 'start_group', ['start_group'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'student_work')
    op.drop_column('course', 'learn_format')
    op.drop_column('course', 'start_group')
    op.drop_column('course', 'for_who')
    op.create_table('student-work',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"student-work_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='student-work_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student-work_pkey')
    )
    op.create_index('ix_student-work_id', 'student-work', ['id'], unique=False)
    op.create_table('learning_fromat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desc_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='learning_fromat_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_fromat_pkey')
    )
    op.create_index('ix_learning_fromat_id', 'learning_fromat', ['id'], unique=False)
    op.drop_index(op.f('ix_student_work_id'), table_name='student_work')
    op.drop_table('student_work')
    op.drop_index(op.f('ix_learn_format_id'), table_name='learn_format')
    op.drop_table('learn_format')
    # ### end Alembic commands ###
